# Generated by Django 4.1.3 on 2022-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='githubUrl',
            field=models.URLField(default='https://github.com/entl'),
        ),
    ]
